export const PH_LOCATION_SEEDS = [
  { id: 'manila', name: 'Manila', region: 'Metro Manila' },
  { id: 'boracay', name: 'Boracay', region: 'Visayas' },
  { id: 'siargao', name: 'Siargao', region: 'Mindanao' },
  { id: 'palawan-el-nido', name: 'El Nido, Palawan', region: 'South Luzon & Bicol' },
  { id: 'palawan-coron', name: 'Coron, Palawan', region: 'South Luzon & Bicol' },
  { id: 'palawan-puerto-princesa', name: 'Puerto Princesa, Palawan', region: 'South Luzon & Bicol' },
  { id: 'cebu-city', name: 'Cebu City', region: 'Visayas' },
  { id: 'moalboal', name: 'Moalboal, Cebu', region: 'Visayas' },
  { id: 'bantayan', name: 'Bantayan Island, Cebu', region: 'Visayas' },
  { id: 'bohol', name: 'Bohol', region: 'Visayas' },
  { id: 'baguio', name: 'Baguio City', region: 'North & Central Luzon' },
  { id: 'batanes', name: 'Batanes', region: 'North & Central Luzon' },
  { id: 'sagada', name: 'Sagada', region: 'North & Central Luzon' },
  { id: 'tagaytay', name: 'Tagaytay', region: 'South Luzon & Bicol' },
  { id: 'vigan', name: 'Vigan, Ilocos Sur', region: 'North & Central Luzon' },
  { id: 'la-union', name: 'La Union', region: 'North & Central Luzon' },
  { id: 'zambales', name: 'Zambales', region: 'North & Central Luzon' },
  { id: 'iloilo', name: 'Iloilo City', region: 'Visayas' },
  { id: 'bacolod', name: 'Bacolod City', region: 'Visayas' },
  { id: 'davao', name: 'Davao City', region: 'Mindanao' },
  { id: 'siquijor', name: 'Siquijor', region: 'Visayas' },
  { id: 'camiguin', name: 'Camiguin', region: 'Mindanao' },
  { id: 'dumaguete', name: 'Dumaguete', region: 'Visayas' },
  { id: 'cagayan-de-oro', name: 'Cagayan de Oro', region: 'Mindanao' },
  { id: 'bicol-legazpi', name: 'Legazpi, Bicol', region: 'South Luzon & Bicol' },
  { id: 'samar', name: 'Samar', region: 'Visayas' },
  { id: 'leyte', name: 'Leyte', region: 'Visayas' },
  { id: 'baler', name: 'Baler, Aurora', region: 'North & Central Luzon' },
  { id: 'batangas', name: 'Batangas', region: 'South Luzon & Bicol' },
]
